config/routes.rb
Houston::Releases::Engine.routes.draw do

  scope "projects/:project_id" do
    get "releases", to: "releases#index", as: :releases

    scope "environments/:environment" do
      get "releases", to: "releases#index"
      post "releases", to: "releases#create"
      get "releases/new", to: "releases#new", as: :new_release
      get "releases/:id", to: "releases#show"
    end
  end

  get "releases/:id", to: "releases#show", as: :release
  get "releases/:id/edit", to: "releases#edit", as: :edit_release
  match "releases/:id", to: "releases#update", via: [:put, :patch]
  delete "releases/:id", to: "releases#destroy"

end

app/models/houston/releases/release.rb
module Houston
  module Releases
    class Release < ActiveRecord::Base
      self.table_name = "releases"

      after_create :load_commits!, :if => :can_read_commits?
      after_create { Houston.observer.fire "release:create", release: self }
      after_save :update_search_vector, :if => :search_vector_should_change?

      belongs_to :project
      belongs_to :user
      belongs_to :deploy
      belongs_to :commit_before, class_name: "Commit"
      belongs_to :commit_after, class_name: "Commit"
      has_and_belongs_to_many :commits, autosave: false # <-- a bug with autosave causes commit_ids to be saved twice

      default_scope { order("created_at DESC") }

      validates_presence_of :user_id
      validates_uniqueness_of :deploy_id, :allow_nil => true
      validates_associated :release_changes



      class << self
        def to_environment(environment_name)
          where(environment_name: environment_name)
        end
        alias :to :to_environment

        def for_projects(*projects)
          ids = projects.flatten.map { |project| project.is_a?(Project) ? project.id : project }
          where(project_id: ids)
        end

        def for_deploy(deploy)
          where(deploy_id: deploy.id)
        end

        def most_recent_commit
          release = where(arel_table[:commit1].not_eq("")).first
          release ? release.commit1 : Houston::NULL_GIT_COMMIT
        end

        def before(time)
          return all if time.nil?
          where(arel_table[:created_at].lt(time))
        end

        def after(time)
          return all if time.nil?
          where(arel_table[:created_at].gt(time))
        end

        def latest
          first
        end

        def earliest
          last
        end

        def with_message
          where arel_table[:message].not_eq("")
        end

        def most_recent
          joins <<-SQL
            INNER JOIN (
              SELECT project_id, environment_name, MAX(created_at) AS created_at
              FROM releases
              GROUP BY project_id, environment_name
            ) AS most_recent_releases
            ON releases.project_id=most_recent_releases.project_id
            AND releases.environment_name=most_recent_releases.environment_name
            AND releases.created_at=most_recent_releases.created_at
          SQL
        end

        def reindex!
          update_all "search_vector = to_tsvector('english', release_changes)"
        end

        def search(query_string)
          config = PgSearch::Configuration.new({against: "plain_text"}, self)
          normalizer = PgSearch::Normalizer.new(config)
          options = { dictionary: "english", tsvector_column: "search_vector" }
          query = PgSearch::Features::TSearch.new(query_string, options, config.columns, self, normalizer)

          excerpt = ts_headline(:release_changes, query,
            start_sel: "<em>",
            stop_sel: "</em>",

            # Hack: show the entire value of `release_changes`
            min_words: 65534,
            max_words: 65535,
            max_fragments: 0)

          columns = (column_names - %w{release_changes search_vector}).map { |column| "releases.\"#{column}\"" }
          columns.push excerpt.as("release_changes")
          where(query.conditions).select(*columns)
        end
      end



      def commit0
        super || commit_before.try(:sha)
      end

      def commit0=(sha)
        super; self.commit_before = identify_commit(sha)
      end

      def commit1
        super || commit_after.try(:sha)
      end

      def commit1=(sha)
        super; self.commit_after = identify_commit(sha)
      end

      def can_read_commits?
        (commit_before.present? || commit0 == Houston::NULL_GIT_COMMIT) && commit_after.present?
      end

      def environment_name=(value)
        super value.downcase
      end



      attr_reader :commit_not_found_error_message



      def released_at
        deploy ? deploy.completed_at : created_at
      end

      def release_date
        released_at.to_date
      end
      alias :date :release_date



      def name
        release_date.strftime("%A, %b %e, %Y")
      end

      def message=(value)
        super value.to_s.strip
      end

      def release_changes
        super.lines.map { |s| Houston::Releases::ReleaseChange.from_s(self, s) }
      end

      def release_changes=(changes)
        super changes.map(&:to_s).join("\n")
      end

      def release_changes_attributes=(params)
        self.release_changes = params.values
          .reject { |attrs| attrs["_destroy"] == "1" }
          .map { |attrs| Houston::Releases::ReleaseChange.new(self, attrs["tag_slug"], attrs["description"]) }
      end



      def build_changes_from_commits
        self.release_changes = commits
          .map { |commit| Houston::Releases::ReleaseChange.from_commit(self, commit) }
          .reject { |change| change.tag.nil? }
      end

      def load_commits!
        self.commits = project.commits.between(commit_before, commit_after)
      end



      def ignore?
        !project.show_release_notes_for?(environment_name)
      end

      def notification_recipients
        @notification_recipients ||= project.followers.unretired
      end



      def update_search_vector
        self.class.where(id: id).reindex!
      end

      def search_vector_should_change?
        (changed & %w{release_changes}).any?
      end


    private

      def identify_commit(sha)
        project.find_commit_by_sha(sha)
      rescue Houston::Adapters::VersionControl::CommitNotFound
        @commit_not_found_error_message = $!.message
        @commit_not_found_error_message << " in the repo \"#{project.repo}\"" if project
        nil
      rescue Houston::Adapters::VersionControl::InvalidShaError
        @commit_not_found_error_message = $!.message
        nil
      end

      # http://www.postgresql.org/docs/9.1/static/textsearch-controls.html#TEXTSEARCH-HEADLINE
      def self.ts_headline(column, query, options={})
        column = arel_table[column] if column.is_a?(Symbol)
        options = options.map { |(key, value)| "#{key.to_s.camelize}=#{value}" }.join(", ")
        tsquery = Arel.sql(query.send(:tsquery))
        Arel::Nodes::NamedFunction.new("ts_headline", [column, Arel::Nodes.build_quoted(tsquery), Arel::Nodes.build_quoted(options)])
      end

    end
  end
end

app/models/houston/releases/release_change.rb
module Houston
  module Releases
      class ReleaseChange
      include ActiveModel::Validations

      validates :description, :length => 1...255
      # validates :tag_slug, :in =>

      ENCODING_PATTERN = /^\[([^\]]*)\] (.*)$/.freeze

      def initialize(release, tag_slug, description)
        @release = release
        @tag_slug = tag_slug
        @description = description[/^.*$/]
      end

      attr_reader :release, :tag_slug, :description

      class << self

        def from_s(release, string)
          new release, *(string.match(ENCODING_PATTERN)[1..2])
        end

        def from_commit(release, commit)
          message = commit.clean_message[0..255]
          message[0] = message[0].upcase if message[0]
          tag = Houston::Releases.config.fetch_tag(commit.tags.first)
          new release, tag.slug, message
        end

      end

      def to_s
        "[#{tag_slug}] #{description}"
      end

      def tag
        Houston::Releases.config.fetch_tag(tag_slug)
      end



      def id
        hash
      end

      def marked_for_destruction?
        false
      end

      def _destroy
        marked_for_destruction?
      end

    end
  end
end

app/controllers/houston/releases/application_controller.rb
module Houston::Releases
  class ApplicationController < ::ApplicationController
    layout "houston/releases/application"
    helper Houston::Releases::ReleaseHelper
  end
end

app/controllers/houston/releases/releases_controller.rb
module Houston
  module Releases
    class ReleasesController < Houston::Releases::ApplicationController
      include UrlHelper
      include ReleaseHelper
      before_action :get_release_and_project, only: [:show, :edit, :update, :destroy]
      before_action :get_project_and_environment, only: [:index, :new, :create]



      def index
        @title = "Releases • #{@project.name}"
        @title << " (#{@environment})" if @environment
        @q = params[:q]
        @q = nil if @q.blank?
        @releases = @project.releases.preload(:deploy).search(@q) if @q

        render partial: (@q ? "houston/releases/releases/results" : "houston/releases/releases/index") if request.xhr?
      end

      def new
        @title = "New Release (#{@environment}) • #{@project.name}"

        @deploy = Deploy.find_by_id(params[:deploy_id])
        @releases = @releases.before(@deploy.completed_at) if @deploy
        @commit0 = params.fetch :commit0, @releases.most_recent_commit
        @commit1 = params.fetch :commit1, @deploy.try(:commit)
        @release = @releases.new(commit0: @commit0, commit1: @commit1, deploy: @deploy)
        authorize! :create, @release

        @manual = params[:manual] == "true" || !@project.has_version_control?

        if @release.can_read_commits?
          @release.load_commits!
          @release.build_changes_from_commits
        end

        @release.release_changes = [Houston::Releases::ReleaseChange.new(@release, "", "")] if @release.release_changes.none?

        if request.headers["X-PJAX"]
          render template: "houston/releases/releases/_new_release", layout: false
        else
          render
        end
      end

      def create
        @release = @releases.new(release_params)
        @release.user = current_user
        authorize! :create, @release

        if @release.save
          Houston.deliver! Houston::Releases::Mailer.release(@release) if params[:send_release_email]

          redirect_to @release
        else
          @commit0 = @release.commit0
          @commit1 = @release.commit1

          if @release.can_read_commits?
            @release.load_commits!
          end

          render action: "new"
        end
      end



      def show
        authorize! :show, @release

        @title = "Release #{@release.release_date.strftime("%b %-d")} • #{@project.name}"

        if request.format.oembed?
          render json: MultiJson.dump({
            version: "1.0",
            type: "link",
            provider_name: "#{@project.slug} / #{@release.environment_name}",
            title: format_release_subject(@release),
            html: format_release_description(@release) })
        end
      end

      def edit
        authorize! :update, @release

        if params[:recreate]
          if @release.can_read_commits?
            @release.load_commits!
            @release.build_changes_from_commits
          end
        end

        @release.release_changes = [Houston::Releases::ReleaseChange.new(@release, "", "")] if @release.release_changes.none?
        @release.valid?
      end

      def update
        authorize! :update, @release

        if @release.update_attributes(release_params)
          redirect_to @release, notice: "Release was successfully updated."
        else
          render action: "edit"
        end
      end

      def destroy
        authorize! :destroy, @release

        @release.destroy

        redirect_to releases_url
      end

    private

      def release_params
        # TODO: Better, stronger params
        params.require(:release).permit!
      end

      def get_release_and_project
        @release = Houston::Releases::Release.find(params[:id])
        @project = @release.project
      end

      def get_project_and_environment
        @project = Project.find_by_slug!(params[:project_id])
        @environment = params[:environment] || @project.environments_with_release_notes.first
        @deploys = @project.deploys
          .completed
          .to(@environment)
          .includes(:commit)
          .includes(:release)
        @releases = @project.releases
          .to(@environment)
          .includes(:project)
          .includes(:deploy)
      end

    end
  end
end

app/helpers/houston/releases/release_helper.rb
module Houston
  module Releases
    module ReleaseHelper
      include Houston::Commits::CommitHelper

      def link_to_release_commit_range(release)
        return "" if release.commit0.blank? && release.commit1.blank?
        link_to_commit_range(release.project, release.commit0, release.commit1)
      end

      def releases_path(project, *args)
        options = args.extract_options!
        environment_name = args.first
        if environment_name
          "/projects/#{project.to_param}/environments/#{environment_name}/releases"
        else
          super(project, options)
        end
      end

      def new_release_url(release, options={})
        super(release.project.to_param, release.environment_name, options.merge(deploy_id: release.deploy_id))
      end

      def format_release_date(date)
        "<span class=\"weekday\">#{date.strftime("%A")}</span> #{date.strftime("%b %e, %Y")}".html_safe
      end

      def format_release_subject(release)
        release.date.strftime("%b %e, %Y • ") + release.released_at.strftime("%-I:%M%p").downcase
      end

      def format_release_description(release)
        ordered_by_tag(release.release_changes)
          .map { |change| "#{change.tag.name.upcase}\t#{change.description}" }
          .join("\r\n")
          .html_safe
      end

      def ordered_by_tag(changes)
        changes.sort_by { |change| change.tag ? change.tag.position : 99 }
      end

      def format_release_age(release)
        format_time_ago release && release.created_at
      end

      def replace_quotes(string)
        h(string).gsub(/&quot;(.+?)&quot;/, '<code>\1</code>').html_safe
      end

      def format_change(change)
        mdown change.description
      end

      def format_change_tag(tag)
        "<div class=\"change-tag\" style=\"background-color: ##{tag.color};\">#{tag.name}</div>".html_safe
      end

      def format_commit(commit)
        message = commit.summary
        message = format_with_tickets_linked(commit.project, message)
        message = mdown(message)
        message
      end

      def format_with_tickets_linked(project, message)
        message = h(message)

        if project.respond_to?(:ticket_tracker_ticket_url)
          message.gsub! Commit::TICKET_PATTERN do |match|
            ticket_number = Commit::TICKET_PATTERN.match(match)[1]
            link_to match, project.ticket_tracker_ticket_url(ticket_number), "target" => "_blank", "rel" => "ticket", "data-number" => ticket_number
          end
        end

        message.gsub! Commit::EXTRA_ATTRIBUTE_PATTERN do |match|
          key, value = match.scan(Commit::EXTRA_ATTRIBUTE_PATTERN).first
          format_extra_attribute(key, value)
        end

        message.html_safe
      end

      def format_extra_attribute(key, value)
        "<span class=\"commit-extra-attribute\"><span class=\"commit-extra-attribute-key\">#{key}</span><span class=\"commit-extra-attribute-value\">#{value}</span></span>"
      end

    end
  end
end

app/views/houston/releases/releases/_changelog.html.erb
<div id="<%= @release.project.slug %>_changelog" class="-houston-changelog">

  <div class="-houston-changelog-day">
    <h4>
      <% if (defined?(draft) && draft) %>
        Draft
      <% else %>
        <%= format_release_date(@release.date) %> &nbsp;&#x3009;
        <%= @release.released_at.strftime("%-I:%M %p") %>
      <% end %>
      <%= link_to "Edit", edit_release_path(@release) if can?(:update, @release) and !(defined?(draft) && draft) %>
    </h4>
  </div>

  <%= div_for @release do %>

    <% unless @release.message.blank? %>
    <div class="release-message">
      <%= mdown(@release.message) %>
    </div>
    <% end %>

    <% if @release.release_changes.any? %>
      <div class="release-changes">
        <% ordered_by_tag(@release.release_changes).each do |change| %>
          <div class="change">
            <%= format_change_tag change.tag %>
            <div class="change-summary"><%= format_change(change) %></div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="release-no-changes">No changes</div>
    <% end %>

    <% unless (defined?(draft) && draft) %>
      <div class="release-detail">
        <%= render partial: "houston/releases/releases/commits", locals: {commits: @release.commits} if can?(:read, Commit) && !for_email? %>
      </div>
    <% end %>

  <% end %>

</div>

app/views/houston/releases/releases/_commits.html.erb
<% if commits.any? %>
<div class="release-detail-section release-commits">
  <h5>
    Commits
    <% if can?(:read, @project.commits.build) %>
      <span class="commit-range"><%= link_to_release_commit_range(@release) %></span>
    <% end %>
  </h5>
  <ul class="commits">
    <% commits.each do |commit|; commit.project = @project %>
      <%= content_tag :li, :id => "commit_#{commit.id}" do %>
        <%= link_to_commit(commit) if github_url?(@project) && !for_email? && can?(:read, commit) %>
        <%= format_commit(commit) %>
      <% end %>
    <% end %>
  </ul>
</div>
<% end %>

app/views/houston/releases/releases/_form.html.erb
<%= form_for @release, :url => @release.new_record? ? releases_path(@project, @environment) : release_path(@release), :html => { :class => "form-horizontal release-form" } do |f| %>
  <%= f.hidden_field :commit0 %>
  <%= f.hidden_field :commit1 %>
  <%= f.hidden_field :deploy_id %>
  <%= hidden_field_tag :recreate, params[:recreate] %>


  <fieldset class="release-detail">
    <div class="control-group">
      <%= f.label :message, :class => "control-label" %>
      <div class="controls">
        <p class="expander optional" data-expand="ticket_message_block">
          <a href="#">Click to add a message to the release</a>
        </p>
        <div id="ticket_message_block" class="collapsed">
          <%= f.text_area :message, :class => "text_field" %>
        </div>
      </div>
    </div>

    <div class="release-detail-section">
      <%= f.label :release_changes, "Changes", :class => "control-label" %>
      <div class="controls changes-nested-editor row-fluid">
        <p class="instructions">Describe, in users&rsquo; terms, what this release changes</p>
        <div id="release_changes" class="changes-nested-editor nested editor"></div>
      </div>
    </div>

    <% if @release.commits.any? %>
    <div class="release-detail-section release-commits">
      <label class="control-label">
        Commits
        <span class="commit-range"><%= link_to_release_commit_range(@release) %></span>
      </label>
      <div class="controls changes-nested-editor">
        <p class="expander" data-expand="commits_block">
          <%= pluralize @release.commits.length, "commits" %> hidden •
          <a href="#">show all</a>
        </p>
        <div id="commits_block" class="collapsed">
          <ul class="commits">
            <% @release.commits.each do |commit| %>
              <%= content_tag :li, :id => "commit_#{commit.id}" do %>
                <%= link_to_commit(commit) if github_url?(@project) && !for_email? && can?(:read, commit) %>
                <%= format_commit(commit) %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <% end %>

    <div class="callout callout-footer">
      <label class="control-label">Actions</label>

      <div class="controls">
      <% if @release.new_record? %>
        <p>
          <label for="send_release_email">
            <input type="checkbox" id="send_release_email" name="send_release_email" value="1" checked="checked" /> Send notifications about this release
          </label>
        </p>
      <% end %>
      </div>

      <div class="controls" style="margin-top: 1.5em">
        <%= f.submit nil, :class => "btn btn-primary" %>
        <%= link_to "Cancel", releases_path(@project), :class => "btn" %>
        <%= link_to "Delete", release_path(@release), :method => "delete", :confirm => "Are you sure?", :class => "btn btn-danger btn-delete" if @release.persisted? && can?(:destroy, @release) %>
      </div>
    </div>
  </fieldset>
<% end %>

<% content_for :javascripts do %>
  <script type="text/javascript">
    $(function() {
      new Houston.Releases.ChangesView({
        el: $('#release_changes')[0],
        tags: <%=raw Houston::Releases.config.change_tags.map { |tag| { slug: tag.slug, name: tag.name } }.to_json %>,
        values: <%=raw @release.release_changes.map { |change| { tagSlug: change.tag_slug, description: change.description } }.to_json %>
      }).render();

      $('[data-expand]').click(function(e) {
        e.preventDefault();

        var $a = $(this),
            $target = $('#' + $a.attr('data-expand'));
        if($target.length) {
          $a.hide();
          $target.slideDown(200, function() {
            $target.find('textarea').autosize();
          });
        }
      });
    });
  </script>
<% end %>

<%= yield :javascripts if request.headers["X-PJAX"] %>

app/views/houston/releases/releases/_index.html.erb
<% if @deploys.none? %>

  <div class="alert alert-info">
    There have been no deploys of <b><%= @project.name %></b> to <b><%= @environment %></b> recorded.
  </div>

<% else %>

  <% date = nil %>
  <div id="<%= @project.slug %>_changelog" class="-houston-changelog">
    <% @deploys.each do |deploy| %>
      <% deploy.project = @project; release = deploy.release %>
      <% next if release.nil? && deploy.commit.nil? %>

      <% if date.nil? || date != deploy.date %>
        <% if date %></div><% end %><%# end .-houston-changelog-day %>
        <div class="-houston-changelog-day">
          <h4><%= format_release_date(date = deploy.date) %></h4>
      <% end %>

      <% unless release %>
        <div class="release release-deploy">
          <p class="release-header">
            <%= deploy.completed_at.strftime("%l:%M %p") %>&nbsp;&nbsp;
            <% deploy.commit.project = @project %>
            Deploy to <%= link_to_commit deploy.commit, style: "float: none;" %>

            <span style="float: right;">
              <%= link_to "New Release", new_release_path(slug: @project.slug, environment: @environment, deploy_id: deploy.id), class: "btn btn-mini btn-default" %>
            </span>
        </div>
      <% else %>
        <%= div_for(release) do %>
          <% release.project = @project %>
          <p class="release-header">
            <%= release.released_at.strftime("%l:%M %p") %>&nbsp;&nbsp;
            <%= link_to "details &rarr;".html_safe, release_url(release) %>

            <% if can?(:read, @project.commits.build) %>
              <span class="commit-range"><%= link_to_release_commit_range(release) %></span>
            <% end %>
          </p>

          <% if release.release_changes.any? %>
            <div class="release-changes">
              <% ordered_by_tag(release.release_changes).each do |change| %>
                <div class="change">
                  <%= format_change_tag change.tag %>
                  <div class="change-summary"><%= format_change(change) %></div>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="release-no-changes">No changes</div>
          <% end %>
        <% end %>
      <% end %>

    <% end %>
    <% if date %></div><% end %><%# end .-houston-changelog-day %>
  </div>

<% end %>

app/views/houston/releases/releases/_new_release.html.erb
<% if !@manual && (@commit0.blank? || @commit1.blank?) %>
  <div class="alert alert-info">
    Please enter a range of commits for this release. <%= link_to "Enter a release manually", {manual: true} %>
  </div>
<% elsif @release.commit_not_found_error_message %>
  <div class="alert alert-error">
    <%= replace_quotes(@release.commit_not_found_error_message) %>
  </div>
<% elsif !@manual && @release.commits.none? %>
  <div class="alert alert-error">
    There are no commits in the repo <code><%= @project.repo %></code> that match <code><%= @commit0 %>...<%= @commit1 %></code>
  </div>
<% else %>
  <%= render partial: "form" %>
<% end %>

app/views/houston/releases/releases/_results.html.erb
<% if @releases.none? %>

  <div class="alert alert-info">
    No results found.
  </div>

<% else %>

  <% date = nil %>
  <div id="<%= @project.slug %>_changelog" class="-houston-changelog release-search-result">
    <% @releases.each do |release| %>
      <% release.project = @project %>

      <% if date.nil? || date != release.date %>
        <% if date %></div><% end %><%# end .-houston-changelog-day %>
        <div class="-houston-changelog-day">
          <h4><%= format_release_date(date = release.date) %></h4>
      <% end %>

      <%= div_for(release) do %>
        <% release.project = @project %>
        <p class="release-header">
          <%= release.released_at.strftime("%l:%M %p") %>&nbsp;&nbsp;
          <%= link_to "details &rarr;".html_safe, release_url(release) %>

          <% if can?(:read, @project.commits.build) %>
            <span class="commit-range"><%= link_to_release_commit_range(release) %></span>
          <% end %>
        </p>

        <div class="release-changes">
          <% ordered_by_tag(release.release_changes).each do |change| %>
            <% if can?(:read, change) %>
              <div class="change">
                <%= format_change_tag change.tag %>
                <div class="change-summary"><%= format_change(change) %></div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>

    <% end %>
    <% if date %></div><% end %><%# end .-houston-changelog-day %>
  </div>

<% end %>

app/views/houston/releases/releases/edit.html.erb
<%= render partial: "projects/header", locals: {project: @project, subtitle: format_release_date(@release.date)} %>

<% if params[:recreate] %>
  <%= link_to "Cancel", edit_release_path(@release), :class => "btn" %>
<% else %>
  <%= link_to "Recreate", edit_release_path(@release, :recreate => true), :class => "btn" %>
<% end %>

<%= render partial: "form" %>

app/views/houston/releases/releases/index.html.erb
<%= render partial: "projects/header", locals: {project: @project, subtitle: "Releases of"} %>

<ul class="nav nav-pills inline">
  <% @project.environments_with_release_notes.each do |environment| %>
    <% if can?(:read, @project.releases.build(environment_name: environment)) %>
      <%= content_tag :li, :class => (@environment == environment ? "active" : nil) do %>
        <% link_to environment.titleize, releases_path(@project, environment: environment) %>
      <% end %>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Release", new_release_path(@project, @environment), :class => 'btn btn-primary' if @environment && can?(:create, Houston::Releases::Release) %>

<form id="search_releases" method="get" class="input-group pull-right">
  <%= search_field_tag :q, @q, autofocus: true %><%=
      hidden_field_tag :environment, @environment %><%=
      submit_tag "Search", class: "btn btn-default" -%>
</form>


<div id="releases" class="release-search-result">
  <%= render partial: (@q ? "houston/releases/releases/results" : "houston/releases/releases/index") %>
</div>

<% content_for :javascripts do %>
<script type="text/javascript">
  $(function() {
    var $form = $('#search_releases');
    $form.submit(function(e) {
      e.preventDefault();
      var url = window.location.pathname + '?' + $form.serialize();
      $form.find('input[type="submit"]').prop('disabled', true);
      $.get(url)
        .success(function(html) {
          $('#releases').html(html);
        })
        .complete(function() {
          $form.find('input[type="submit"]').prop('disabled', false);
        });
    });
  });
</script>
<% end %>

app/views/houston/releases/releases/new.html.erb
<%= render partial: "projects/header", locals: {project: @project, subtitle: "New Release of" } %>

<% if @deploy && @deploy.release && @deploy.release.persisted? %>

  <div class="alert alert-error">
    Release notes have already been created for this deploy.
    <%= link_to "Edit", edit_release_path(@deploy.release) %>
  </div>

<% elsif !@project.has_version_control? %>

  <%= render "configuration_error/no_version_control",
      message: "To pull release notes from your commit messages, we need to know where to find the project's repo." %>

<% elsif @project.repo.nil? %>

  <%= render "configuration_error/invalid_repo" %>

<% elsif @manual %>

  <div class="form-horizontal callout callout-banner new-release">
    <div class="controls">
      <h3>New Manual Release</h3>
      <%= link_to "Create a release from a commit range", {manual: false} %>
    </div>
  </div>

<% else %>

  <form accept-charset="UTF-8" action="<%= new_release_path(@project, @environment) %>" class="form-horizontal callout callout-banner new-release pjax" method="get" id="new_release_commit_range_form">
    <div class="controls">
      <h3>New Release to <%= @environment.titleize %></h3>
      <p>Create a new release for the following commits</p>
      <%= hidden_field_tag :deploy_id, params[:deploy_id] %>
      <%= text_field_tag :commit0, @commit0, :class => "text_field", size: 8 %>
      ...
      <%= text_field_tag :commit1, @commit1, :class => "text_field", size: 8 %>
      <%= submit_tag "Continue", :name => nil, :class => "btn btn-primary" %>
    </div>
  </form>

<% end %>

<div id="new_release_form">
  <%= render partial: "houston/releases/releases/new_release" %>
</div>

<% content_for :javascripts do %>
<script type="text/javascript">
  $(function() {
    $('form.pjax').submit(function(e) {
      e.preventDefault();
      var $form = $(this),
          url = $form.attr('action') + '?' + $form.serialize();
      $.pjax({
        url: url,
        container: '#new_release_form'
      });
      return false;
    });
  });
</script>
<% end %>

app/views/houston/releases/releases/show.html.erb
<% content_for :meta do %>
  <%= link_to_oembed release_url(@release) %>
  <%= tag "meta", property: "og:type", content: "website" %>
  <%= tag "meta", property: "og:site_name", content: "#{@project.slug} / #{@release.environment_name}" %>
  <%= tag "meta", property: "og:title", content: format_release_subject(@release) %>
  <%= tag "meta", property: "og:description", content: format_release_description(@release) %>
  <%= tag "meta", property: "og:url", content: release_url(@release) %>
<% end %>

<%= render partial: "projects/header", locals: {project: @project, subtitle: "Release of"} %>

<%= render partial: "houston/releases/releases/changelog" %>